language: minimal
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_deploy:
  - openssl aes-256-cbc -K $encrypted_52b98b8c88bc_key -iv $encrypted_52b98b8c88bc_iv -in travis.key.enc -out ~/travis.key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/travis.key
  - ssh-add ~/travis.key
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r srv/* $DEPLOY_HOST:$DEPLOY_PATH/
